apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: argocd-s
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: ghcr.io/adapter877/sci-borrow:b3865fd3004b87c43e339be4a3a080611129b422
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
